/* LETONICE SPOLEČNĚ — accessible, progressively enhanced interactions. */
(function(){
'use strict';
const $=(s)=>document.querySelector(s),$$=(s)=>Array.from(document.querySelectorAll(s));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const toggle=$('.nav-toggle'),menu=$('#nav-menu');
function closeMenu(){if(!toggle||!menu)return;menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Otevřít menu');}
if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Zavřít menu':'Otevřít menu');});menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){closeMenu();toggle.focus();}});document.addEventListener('click',e=>{if(!e.target.closest('.nav'))closeMenu();});}
const start=Date.parse('2026-10-09T14:00:00+02:00'),finish=Date.parse('2026-10-10T14:00:00+02:00');
function tick(){if(!$('#cd-days'))return;const diff=Math.max(0,start-Date.now());$('#cd-days').textContent=Math.floor(diff/86400000);$('#cd-hours').textContent=Math.floor(diff/3600000)%24;$('#cd-mins').textContent=Math.floor(diff/60000)%60;if(Date.now()>=start){$('#countdown').innerHTML='<p class="election-state">'+(Date.now()<finish?'Probíhají volební dny':'Hlasování skončilo')+'</p>';clearInterval(timer);}}
let timer=setInterval(tick,30000);tick();

/* ---------- mapa: data v assets/data/mapa-letonice.js ---------- */
const DATA=window.LETONICE_MAP_DATA||{points:{},places:[]};
const pointMeta=DATA.points||{},places=DATA.places||[];
const wholeNotes={'4':'Bod 4 · Řádné hospodaření se týká majetku celé obce – na mapě proto nemá vlastní značku.'};
const village=[[49.1638,16.9490],[49.1812,16.9725]];
let townMap=null,activePoint=null,activePlace=null,markers={},zoneByCode={},zoneLayer=null,vetrLayer=null;
const byPoint=(p)=>places.filter(x=>x.point===p);
const placeById=(id)=>places.find(x=>x.id===id);
function fit(b,maxZoom){if(townMap)townMap.fitBounds(b,{padding:[36,36],maxZoom:maxZoom||17,animate:!reduced});}
function placeBounds(p){const b=L.latLngBounds([[p.lat,p.lon]]);(p.codes||[]).forEach(c=>{if(zoneByCode[c])b.extend(zoneByCode[c].getBounds());});if(p.polyKey&&DATA[p.polyKey])b.extend(L.latLngBounds(DATA[p.polyKey]));return b;}
function pointBounds(point){const list=byPoint(point);if(!list.length)return null;const b=L.latLngBounds([]);list.forEach(p=>b.extend(placeBounds(p)));return b;}
function setStatus(t){const s=$('#map-status');if(s)s.textContent=t;}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function popupHtml(p){let h='<b>'+esc(p.name)+'</b>';if(p.note)h+='<br>'+esc(p.note);if(p.approx)h+='<br><small class="popup-approx">Poloha je orientační – upřesníme podle místní znalosti.</small>';h+='<br><a href="#bod-'+p.point+'">Přečíst bod '+p.point+' programu →</a>';if(p.src)h+='<br><a href="'+esc(p.src)+'" target="_blank" rel="noopener">'+esc(p.srcLabel||'Zdroj polohy')+' ↗</a>';return h;}
function renderSublist(point){const box=$('#map-sublist');if(!box)return;box.replaceChildren();const list=point?byPoint(point):[];box.hidden=!list.length;const meta=pointMeta[point]||{};list.forEach(p=>{const b=document.createElement('button');b.type='button';b.dataset.place=p.id;b.style.setProperty('--pc',meta.color||'#771c31');b.setAttribute('aria-pressed',String(p.id===activePlace));b.textContent=p.name+(p.approx?' ≈':'');if(p.approx)b.title='Poloha je orientační';b.addEventListener('click',()=>{initMap();focusPlace(p.id);});box.append(b);});}
function restyle(){if(zoneLayer){const on=activePoint==='5',off=!!activePoint&&!on;zoneLayer.setStyle({fillOpacity:on?.45:(off?.1:.28),weight:on?2.5:(off?1:2),opacity:on?.95:(off?.45:.8)});}if(vetrLayer){const on=activePoint==='7',off=!!activePoint&&!on;vetrLayer.setStyle({fillOpacity:on?.38:(off?.1:.22),weight:on?3:(off?1:2)});}Object.entries(markers).forEach(([id,m])=>{const el=m.getElement();if(!el)return;const p=placeById(id);el.classList.toggle('is-active',!!activePoint&&p.point===activePoint);el.classList.toggle('is-dim',!!activePoint&&p.point!==activePoint);});}
function select(point,move){activePoint=point||null;activePlace=null;$$('.program-item').forEach(el=>el.classList.toggle('active',el.dataset.point===activePoint));$$('[data-map-point]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mapPoint===activePoint)));restyle();renderSublist(activePoint);const meta=pointMeta[activePoint]||{label:''};if(!activePoint)setStatus('Vyberte bod programu nebo místo na mapě.');else if(byPoint(activePoint).length)setStatus('Bod '+activePoint+' · '+meta.label+' · '+byPoint(activePoint).length+' míst na mapě. Klikněte na značku nebo na název místa.');else setStatus(wholeNotes[activePoint]||('Bod '+activePoint+' · '+meta.label));if(townMap&&move){townMap.closePopup();const b=activePoint?pointBounds(activePoint):null;if(b)fit(b,activePoint==='7'?15:16);else fit(village);}}
function openItem(point){const item=$('.program-item[data-point="'+point+'"]');if(item&&!item.open)item.open=true;}
function focusPlace(id){const p=placeById(id);if(!p||!townMap)return;if(activePoint!==p.point){openItem(p.point);select(p.point,false);}activePlace=id;$$('#map-sublist button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.place===id)));if(p.codes||p.polyKey)fit(placeBounds(p),17);else townMap.setView([p.lat,p.lon],17,{animate:!reduced});const m=markers[id];if(m)m.openPopup();setStatus(p.name+(p.note?' · '+p.note:'')+(p.approx?' Poloha je orientační.':''));}
function openPoint(point,scroll){const item=$('.program-item[data-point="'+point+'"]');if(!item)return;item.open=true;select(point,true);if(scroll)item.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});}
function initMap(){const el=$('#town-map');if(!el||townMap)return;if(!window.L){el.innerHTML='<p class="map-loading">Mapu se nepodařilo načíst. Použijte odkaz na velkou mapu níže; program je dostupný i bez mapy.</p>';return;}
el.replaceChildren();townMap=L.map(el,{scrollWheelZoom:false,zoomControl:true,zoomSnap:0.5});fit(village);const layer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> · plochy bydlení: <a href="https://www.letonice.cz/uzemni-plan-obce">ÚP Letonice</a>'}).addTo(townMap);L.control.scale({imperial:false}).addTo(townMap);let failed=0;layer.on('tileerror',()=>{if(++failed>=3)setStatus('Mapový podklad je nyní nedostupný. Zkuste otevřít velkou mapu odkazem níže.');});layer.on('tileload',()=>{failed=0;});
if(DATA.zones){zoneLayer=L.geoJSON(DATA.zones,{style:{color:'#7E3FA8',weight:2,opacity:.8,fillColor:'#7E3FA8',fillOpacity:.28,dashArray:'5 4'},onEachFeature:(f,l)=>{const c=f.properties.code;zoneByCode[c]=l;const ha=(f.properties.area_m2/10000).toFixed(1).replace('.',',');l.bindPopup('<b>Plocha '+esc(c)+'</b> – bydlení v rodinných domech<br>cca '+ha+' ha · Územní plán Letonice, právní stav po změně č. 1 (2016)<br><small class="popup-approx">Zákres je orientační, přenesený z výkresu územního plánu.</small><br><a href="#bod-5">Přečíst bod 5 programu →</a><br><a href="https://www.letonice.cz/uzemni-plan-obce" target="_blank" rel="noopener">Územní plán na webu obce ↗</a>');l.on('click',()=>{if(activePoint!=='5'){openItem('5');select('5',false);}});}}).addTo(townMap);}
if(DATA.vetrniky){vetrLayer=L.polygon(DATA.vetrniky,{color:'#2E8B45',weight:2,fillColor:'#2E8B45',fillOpacity:.22}).addTo(townMap);const vp=placeById('vetrniky');if(vp)vetrLayer.bindPopup(popupHtml(vp));vetrLayer.on('click',()=>{if(activePoint!=='7'){openItem('7');select('7',false);}});}
places.forEach(p=>{const meta=pointMeta[p.point]||{color:'#771c31'};const m=L.marker([p.lat,p.lon],{icon:L.divIcon({className:'place-marker'+(meta.dark?' dark':'')+(p.approx?' approx':''),html:'<b style="background:'+meta.color+'">'+p.point+'</b>',iconSize:[32,32],iconAnchor:[16,16]}),title:p.name,alt:p.name,keyboard:true}).addTo(townMap);m.bindPopup(popupHtml(p));m.bindTooltip(p.name,{direction:'top',offset:[0,-14]});m.on('click',()=>{focusPlace(p.id);});markers[p.id]=m;});
if(window.ResizeObserver)new ResizeObserver(()=>townMap.invalidateSize({pan:false})).observe(el);if(activePoint)select(activePoint,true);}
if($('#town-map')){if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){initMap();io.disconnect();}},{rootMargin:'300px'});io.observe($('#town-map'));}else initMap();}
$$('[data-map-point]').forEach(b=>b.addEventListener('click',()=>{initMap();if(activePoint===b.dataset.mapPoint){select(null,true);return;}openPoint(b.dataset.mapPoint,false);}));
$('#map-reset')?.addEventListener('click',()=>{initMap();select(null,true);});
$$('.program-item').forEach(item=>{item.addEventListener('toggle',()=>{if(item.open&&activePoint!==item.dataset.point)select(item.dataset.point,true);});});
function hash(){const m=/^#bod-(\d+)$/.exec(location.hash);if(m)openPoint(m[1],true);}hash();window.addEventListener('hashchange',hash);

/* ---------- koupaliště: přepínání pohledů ---------- */
const pool={archive:{src:'assets/img/koupaliste/koupaliste-provoz.jpg',alt:'Archivní fotografie letonického koupaliště v dobách provozu',title:'Koupaliště, jak si ho pamatujeme.',caption:'Archivní fotografie z dob provozu, nikoli současný stav areálu.'},proposal:{src:'assets/img/koupaliste-studie-2030-full.jpg',alt:'Pracovní návrh uspořádání areálu koupaliště od Jana Ježorka, 2026',title:'Pracovní návrh · Jan Ježorek, 2026.',caption:'Jedna z variant k veřejné diskusi. Zobrazené vybavení ani rozměry nejsou schváleným projektem.'},study:{src:'assets/img/koupaliste/studie-starsi-vizualizace.jpg',alt:'Architektonická studie sportovně relaxačního areálu Letonice od ateliéru DIMENSE z května 2021',title:'Starší architektonická studie · DIMENSE, 2021.',caption:'Vizualizace z dodaných podkladů. Není fotografií současného stavu ani novým schváleným návrhem.'}};
$$('[data-pool]').forEach(b=>b.addEventListener('click',()=>{const p=pool[b.dataset.pool];$$('[data-pool]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));$('#pool-image').src=p.src;$('#pool-image').alt=p.alt;$('#pool-link').href=p.src;$('#pool-link').dataset.caption=p.title+' '+p.caption;const caption=$('#pool-caption');caption.replaceChildren();const strong=document.createElement('b');strong.textContent=p.title;caption.append(strong,' '+p.caption);}));

/* ---------- lightbox ---------- */
const dialog=$('#lightbox');let group=[],index=0,opener=null;
function displayImage(){const link=group[index];dialog.querySelector('img').src=link.href;dialog.querySelector('img').alt=link.dataset.caption||link.querySelector('img')?.alt||'';dialog.querySelector('figcaption').textContent=link.dataset.caption||'';$('.lightbox-count').textContent=(index+1)+' / '+group.length;$('.lightbox-navigation').hidden=group.length<2;}
function step(d){index=(index+d+group.length)%group.length;displayImage();}
if(dialog&&typeof dialog.showModal==='function'){$$('a.lightbox').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();opener=a;const gallery=a.closest('.gallery');group=gallery?Array.from(gallery.querySelectorAll('a.lightbox')):[a];index=group.indexOf(a);displayImage();dialog.showModal();}));$('.lightbox-prev')?.addEventListener('click',()=>step(-1));$('.lightbox-next')?.addEventListener('click',()=>step(1));$('.lightbox-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}});dialog.addEventListener('close',()=>{dialog.querySelector('img').removeAttribute('src');opener?.focus({preventScroll:true});});}

/* ---------- zvýraznění aktivní sekce v menu ---------- */
if('IntersectionObserver'in window){const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('.nav-links a').forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}}),{rootMargin:'-20% 0px -60% 0px'});$$('main>section[id]').forEach(s=>navObserver.observe(s));}
})();
